# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='place_images')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('rate', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nazwa', max_length=128)),
                ('arrival', models.DateField(blank=True)),
                ('departure', models.DateField(blank=True)),
                ('latitude', models.FloatField(blank=True)),
                ('longtitude', models.FloatField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='my_travel_story/static/profile_images/no_image.png', upload_to='my_travel_story/static/profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='user_profile_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_travel_story.UserProfile'),
        ),
        migrations.AddField(
            model_name='picture',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_travel_story.Place'),
        ),
    ]
