# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_travel_story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='place_images')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='picture',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_travel_story.Picture'),
        ),
    ]
