# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_travel_story', '0003_auto_20161123_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_travel_story.Place'),
        ),
    ]
